version: "3.8"

services:
  slideshow:
    build: .
    container_name: slideshow-app
    restart: unless-stopped
    ports: 
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - IMAGES_PATH=/app/images
    volumes:
      - ${IMAGES_PATH}:/app/images